language: python

dist: trusty
sudo: false
group: beta

cache:
  - pip

install:
  - pip install simplejson

script:
  - python checkjson.py && coverage.sh
  - ./tidy-json.sh && git diff --exit-code

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
