language: python

dist: trusty
sudo: false
group: beta

addons:
  apt:
    packages:
    - dos2unix

cache:
  - pip

install:
  - pip install simplejson

script:
  - python checkjson.py && python coverage.py | sort -n
  - ./tidy-json.sh && git diff --exit-code

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
